//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightAlert
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportEntities1 : DbContext
    {
        public AirportEntities1()
            : base("name=AirportEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IncomingPlane> IncomingPlanes { get; set; }
        public virtual DbSet<MajorAirport> MajorAirports { get; set; }
        public virtual DbSet<OutgoingPlane> OutgoingPlanes { get; set; }
    }
}
