//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightAlert
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutgoingPlane
    {
        public int Plane_ID { get; set; }
        public string Name { get; set; }
        public int Delayed { get; set; }
        public string Destination { get; set; }
        public System.DateTime Depature_DateTime { get; set; }
    }
}
